# -*- coding: utf-8 -*-
from vindauga.constants.keys import *

moddedKeyCodes: dict[int, list] = {
    ord('A'): [0, kbCtrlA, kbAltA],
    ord('B'): [0, kbCtrlB, kbAltB],
    ord('C'): [0, kbCtrlC, kbAltC], ord('D'): [0, kbCtrlD, kbAltD],
    ord('E'): [0, kbCtrlE, kbAltE], ord('F'): [0, kbCtrlF, kbAltF],
    ord('G'): [0, kbCtrlG, kbAltG], ord('H'): [0, kbCtrlH, kbAltH],
    ord('I'): [0, kbCtrlI, kbAltI], ord('J'): [0, kbCtrlJ, kbAltJ],
    ord('K'): [0, kbCtrlK, kbAltK], ord('L'): [0, kbCtrlL, kbAltL],
    ord('M'): [0, kbCtrlM, kbAltM], ord('N'): [0, kbCtrlN, kbAltN],
    ord('O'): [0, kbCtrlO, kbAltO], ord('P'): [0, kbCtrlP, kbAltP],
    ord('Q'): [0, kbCtrlQ, kbAltQ], ord('R'): [0, kbCtrlR, kbAltR],
    ord('S'): [0, kbCtrlS, kbAltS], ord('T'): [0, kbCtrlT, kbAltT],
    ord('U'): [0, kbCtrlU, kbAltU], ord('V'): [0, kbCtrlV, kbAltV],
    ord('W'): [0, kbCtrlW, kbAltW], ord('X'): [0, kbCtrlX, kbAltX],
    ord('Y'): [0, kbCtrlY, kbAltY], ord('Z'): [0, kbCtrlZ, kbAltZ],
    ord('1'): [0, 0, kbAlt1], ord('2'): [0, 0, kbAlt2],
    ord('3'): [0, 0, kbAlt3], ord('4'): [0, 0, kbAlt4],
    ord('5'): [0, 0, kbAlt5], ord('6'): [0, 0, kbAlt6],
    ord('7'): [0, 0, kbAlt7], ord('8'): [0, 0, kbAlt8],
    ord('9'): [0, 0, kbAlt9], ord('0'): [0, 0, kbAlt0],
    ord(' '): [0, 0, kbAltSpace], ord('-'): [0, 0, kbAltMinus],
    ord('='): [0, 0, kbAltEqual],
    kbF1: [kbShiftF1, kbCtrlF1, kbAltF1], kbF2: [kbShiftF2, kbCtrlF2, kbAltF2],
    kbF3: [kbShiftF3, kbCtrlF3, kbAltF3], kbF4: [kbShiftF4, kbCtrlF4, kbAltF4],
    kbF5: [kbShiftF5, kbCtrlF5, kbAltF5], kbF6: [kbShiftF6, kbCtrlF6, kbAltF6],
    kbF7: [kbShiftF7, kbCtrlF7, kbAltF7], kbF8: [kbShiftF8, kbCtrlF8, kbAltF8],
    kbF9: [kbShiftF9, kbCtrlF9, kbAltF9], kbF10: [kbShiftF10, kbCtrlF10, kbAltF10],
    kbF11: [kbShiftF11, kbCtrlF11, kbAltF11], kbF12: [kbShiftF12, kbCtrlF12, kbAltF12],
    kbEsc: [0, 0, kbAltEsc], kbBackSpace: [0, kbCtrlBackSpace, kbAltBack],
    kbTab: [kbShiftTab, kbCtrlTab, kbAltTab], kbEnter: [0, kbCtrlEnter, kbAltEnter],
    kbHome: [0, kbCtrlHome, kbAltHome], kbUp: [0, kbCtrlUp, kbAltUp],
    kbPgUp: [0, kbCtrlPgUp, kbAltPgUp], kbLeft: [0, kbCtrlLeft, kbAltLeft],
    kbRight: [0, kbCtrlRight, kbAltRight], kbEnd: [0, kbCtrlEnd, kbAltEnd],
    kbDown: [0, kbCtrlDown, kbAltDown], kbPgDn: [0, kbCtrlPgDn, kbAltPgDn],
    kbIns: [kbShiftIns, kbCtrlIns, kbAltIns], kbDel: [kbShiftDel, kbCtrlDel, kbAltDel],
}
